#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Jenssegers\Optimus\Commands\SparkCommand;
use Symfony\Component\Console\Application;

$application = new Application;
$application->add(new SparkCommand);
$application->run();
