name: tests

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        php: [7.3, 7.4]
        composer-flag: [prefer-lowest, prefer-stable]

    name: php v${{ matrix.php }} - ${{ matrix.composer-flag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pdo
          tools: composer:v2

      - name: Install dependencies
        run: composer update --${{ matrix.composer-flag }} --no-interaction --no-progress

      - name: Execute tests
        run: |
          mkdir -p build/logs
          ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
          ./vendor/bin/php-coveralls -v
